version: '3.7'
services: 
    laravel-db:
        image: mysql:5.7 
        environment: 
            MYSQL_ROOT_PASSWORD: admin.2021
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: lara 
            MYSQL_PASSWORD: lara2021
        ports: 
            - 33069:3306
        volumes: 
            - ./database/schemas/:/var/lib/mysql
        networks: 
            laravel_net:
                ipv4_address: 172.21.100.9
    laravel-prod:
        build: 
            context: ./  #indica donde esta o dockerfile
            dockerfile: Dockerfile
        ports: 
            - 8200:80
        volumes: 
            - ./e_lardock:/var/www/
            - ./e_lardock/public:/var/www/html
        networks: 
            laravel_net:
                ipv4_address: 172.21.100.10
        depends_on: 
            - laravel-db
volumes: 
    e_lardock:
    database:
networks: 
    laravel_net:
        driver: bridge
        ipam:
            driver: default
            config: 
                -
                    subnet: 172.21.100.0/24